from langchain.prompts import PromptTemplate

instruction = """
for a given database with language {dialect}
you are given the following items
The question asked by a user: {question}
The {dialect} query generated for the question: {query}
The result returned by the database for the query: {result}

**Instructions**:
1. Considering all three factors generate a concise , well structured and formatted summary of the 
result generated by the database. 
2. If the Query is an empty string, Simply RETURN THE RESULT provided in this prompt as the answer. DO NOT CHANGE IT in any way
3. Return only the summary in the form of a string
4. Keep the summmary as short as possible while clearly explainng the result such that it is a valid answer to the question {question}
5. Read the question carefully if the complete answer is required or not. If NOT then return only top 5 values. Otherwise return all the values


"""

prompt = PromptTemplate.from_template(instruction)